### ISSUE TITLE
Genesis mismatch

### ISSUE THREAD

**Issue by eclipsevortex** [RaoFoundation/subtensor#587]
### Describe the bug

When starting a local subtensor on testnet, i get a lot of 
`Report 12D3KooWM4hxkTJB1a8W5hdDPCh9GdRYuk2QghYLAG9dWJd65ZKy: -2147483648 to -2147483648. Reason: Genesis mismatch. Banned, disconnecting.?`

I have not investigate dvery far but i can still run some btcli command like `btcli subnet list --netuid 92 --subtensor.network`

### To Reproduce

Start a local subtensor

### Expected behavior

I do not expect these errors

### Environment

testnet

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Thank you for posting @eclipsevortex

**Comment by distributedstatemachine** [comment]
@eclipsevortex this should have been fixed. can you confirm you are no longer getting this ?

**Comment by goshasty** [comment]
I still have this bug on mainnet lite node either source code or docker installation

**Comment by elesiuta** [comment]
I am also getting this error with `./scripts/run/subtensor.sh -e docker --network mainnet --node-type lite` running on ubuntu 22.04, both on a machine where this was previously working, and a fresh installation. I tried both the latest version, and some previously known working versions which are now giving me this error.

I have a machine I started 10 days ago on adad4fddb4576d3a863594897e3420e0807024a2 which is still running fine. This issue just started happening for me yesterday on any instances which I've (re)started.

**Comment by HudsonGraeme** [comment]
Using the `devnet-ready` branch does not resolve this issue either. Again on Ubuntu 22.04, fresh install
