### ISSUE TITLE
Launching local nodes for testnet and mainnet doesn't work

### ISSUE THREAD

**Issue by gztensor** [RaoFoundation/subtensor#943]
These instructions don't work anymore. We need to either update documentation or fix scripts (or both):

https://docs.bittensor.com/subtensor-nodes/using-source#lite-node-on-testchain

**Comment by ales-otf** [comment]
The issue is fixed in https://github.com/opentensor/subtensor/pull/930

In the documentation, the command to compile the node ([step 5 here](https://docs.bittensor.com/subtensor-nodes/using-source#compile-subtensor-code)) should be changed to:

```
cargo build -p node-subtensor --profile=production --features=metadata-hash
```

**Comment by jp-blockwise** [comment]
What about dockerised setup? It still throws errors, even with changes from #930 .

> 2024-11-08 18:49:51 Cannot create a runtime error=Other("runtime requires function imports which are not present on the host: 'env:ext_benchmarking_read_write_count_version_1', 'env:ext_benchmarking_get_read_and_written_keys_version_1', 'env:ext_benchmarking_wipe_db_version_1', 'env:ext_benchmarking_set_whitelist_version_1', 'env:ext_benchmarking_proof_size_version_1', 'env:ext_benchmarking_commit_db_version_1', 'env:ext_benchmarking_reset_read_write_count_version_1', 'env:ext_benchmarking_add_to_whitelist_version_1', 'env:ext_benchmarking_current_time_version_1'")
